### ISSUE TITLE
Single quote within double quotes

### ISSUE THREAD

**Issue by juergba** [cdhowie/shell-parser#1]
I'm currently testing your shell parser to evtl. use it for a PR in yargs-parser.
On git bash, Windows 10.
I'm using `String.raw()` since bash seems to handle the options as raw strings as well.

```js
const shellParser = require('shell-parser');
let str = String.raw`a "b\'c" d`;
let res = shellParser(str);
console.log(res);
```
Output:
- `process.argv`: `[..., ..., 'a', "b\\'c", 'd']`
- `res`: `[ 'a', "b'c", 'd' ]`

Is this a bug, or does the output depend on the specific shell I'm using?

**Comment by cdhowie** [comment]
The output does not depend on your shell. Arguments are parsed using a simplified version of the algorithm most POSIX shells use.

Can you clarify for me how you expected this input to be parsed?

**Comment by juergba** [comment]
@cdhowie I don't remember, it's too long ago.
I had selected _arrgv_ for my PR in _yargs-parser_, which I closed meanwhile.
Thanks for your reply, I'm closing this PR.
